### ISSUE TITLE
No licence provided

### ISSUE THREAD

**Issue by Sycrosity** [chrrs/limbo#1]
@chrrs - Despite there having been no commits for a year, I was wondering if a licence file could be added so that people like me (attempting to make a project very similar to this one and struggling) could leech some code for their own projects? It's always somewhat unnerving having to risk using code from a repo with no license, even if it seems intended to be open source.

**Comment by chrrs** [comment]
Yes! I never intended this to reach anyone really, so I've never bothered adding a license, but that makes sense. I've added an MIT license to the project now! :)

**Comment by Sycrosity** [comment]
Thanks so much! This is a really interesting project idea and I'm glad I am able to try and build it myself with the help of your code :)
